export const CARRIERS = [
  { name: "DHL" },
  { name: "DHL VN" },
  { name: "DHL SG" },
  { name: "DHL ECOM" },
  { name: "FEDEX" },
  { name: "FEDEX VN" },
  { name: "FEDEX SG" },
  { name: "CT" },
  { name: "CT US" },
  { name: "CT EU" },
  { name: "CT AU" },
  { name: "CT CA" },
  { name: "UPS" },
  { name: "UPS VN" },
  { name: "UPS SG" },
  { name: "TNT" },
  { name: "CLE" },
  { name: "Other" },
];
